### ISSUE TITLE
Add typescript definition

### ISSUE THREAD

**Issue by Schlumpf9** [DaniSchenk/moment-feiertage#10]
Hey,
it would be great if the project contains a typescript index.d.ts file. So in typescript projects as in Angular the compiler doesn't claim that the function isHoliday doesn't exist.

**Comment by DaniSchenk** [comment]
hey @Schlumpf9, I will come up with a solution in a few days and will let you know when there's a new release.

**Comment by DaniSchenk** [comment]
hey @Schlumpf9 , I'm trying to rewrite the plugin with TypeScript. Unfortunately I'm still trying... 😥
It would be great if anyone could help solving my issue https://github.com/moment/moment/issues/5341#issue-546064276 in the official moment repo

**Comment by Schlumpf9** [comment]
I was able to compile my Angular project with the following definitions:

_types/moment/index.d.ts_
```
import moment = require('moment');
export = moment;

declare module 'moment' {
    interface MomentHolidayResult {
        allStates: boolean,
        holidayName: string,
        holidayStates: Array<string>,
        testedStates: Array<string>
    }

    interface Moment {
        isHoliday(_states?: string | Array<string>): MomentHolidayResult;
    }
}
```

**Comment by DaniSchenk** [comment]
@Schlumpf9 you imported the module in your `.ts` like this, right?
```
import { Component, OnInit } from '@angular/core';
import * as moment from 'moment-feiertage';
```
Do you know how to import `moment-feiertage` AND 'moment', so that `moment-feiertage` is more like a extension to `moment` than a replacement?
```
import { Component, OnInit } from '@angular/core';
import * as moment from 'moment';
import 'moment-feiertage';

@Component({...})
export class AppComponent implements OnInit {
  ngOnInit(): void {
    console.log(moment());
    console.log(moment().isHoliday());
  }
}
```
The replacement approach (first) works fine. The extension approach thows this error:
```
error TS2339: Property 'isHoliday' does not exist on type 'Moment'.
```
