### ISSUE TITLE
Maria Himmelfahrt in Bayern

### ISSUE THREAD

**Issue by TobiasMalikowski** [DaniSchenk/moment-feiertage#14]
Hi @DaniSchenk,

erstmal vielen Dank, dass du dir die Mühe gemacht hast ein Plugin für die deutschen Feiertage zu schreiben und es dann der Community zur Verfügung stellst :)

Da du ja selbst aus München kommst, bist du bestimmt selbst schon über den Fall gestolpert, dass du Maria Himmelfahrt gerne als Feiertag betrachten möchtest da er [fast](https://www.swp.de/imgs/07/6/8/7/0/8/6/6/0/tok_921e1a92a4ce155acd98af9e762e92b2/w1068_h601_x750_y416_3318e08c5303126c.png) in ganz Bayern ein Feiertag ist. 

Aus deiner Dokumentation
`
const isHolidayInBavaria = moment('2017-08-15').isHoliday('BY');
// returns false - is not a holiday in BY
`

Gibt es eine Methode mit der sich dieses Verhalten steuern lässt oder wie handhabst du solche Fälle.

Danke für deine Zeit.

Liebe Grüße

Tobi

**Comment by DaniSchenk** [comment]
Hey,

> erstmal vielen Dank, dass du dir die Mühe gemacht hast ein Plugin für die deutschen Feiertage zu schreiben und es dann der Community zur Verfügung stellst :)

Gern, hat sich einfach mal so ergeben...


> Da du ja selbst aus München kommst, bist du bestimmt selbst schon über den Fall gestolpert, dass du Maria Himmelfahrt gerne als Feiertag betrachten möchtest da er fast in ganz Bayern ein Feiertag ist.

Das Problem kenne ich, denn es gibt derzeit (laut [Wikipedia](https://de.wikipedia.org/wiki/Gesetzliche_Feiertage_in_Deutschland)) vier solcher Tage in unterschiedlichen Bundesländern. Da dieses Plugin für ganz Deutschland gilt, habe ich mich dazu entschlossen nur eindeutige Feiertage aus der Wikipedia zu nehmen, um Verwirrungen und hoher Wartung vorzubeugen. Ich hoffe du verstehst das.

> Gibt es eine Methode mit der sich dieses Verhalten steuern lässt oder wie handhabst du solche Fälle.

Es gibt bestimmt viele Möglichkeiten das Problem anzugehen. Eine einfache wäre beispielsweise dir einen Fork des Repos zu erstellen und den Code abzuändern, sodass _Mariä Himmelfahrt_ bei dir immer ein Feiertag in Bayern ist. Ist quick and dirty, stimmt dann für manche Gemeinden nicht.

Alle Daten der Gemeinden in Bayern zu sammeln, die _Mariä Himmelfahrt_ feiern (oder nicht) und dann Vergleiche mit dem Standort deiner Nutzer oder Software zu ziehen, ist glaube ich ziemlich aufwendig. Denn du müsstest eben auch bestimmen können, für welche Gemeinde dein Nutzer oder deine Software die Feiertage ausgeben soll...

Ich hoffe ich konnte dir ein bisschen weiter helfen.

✌

**Comment by TobiasMalikowski** [comment]
Danke für deine schnelle Rückmeldung. Ich verstehe wieso du dass Plugin so geschrieben hast, ich hätte es wahrscheinlich genauso gemacht.

Ich denke für unseren Fall werden einfach eine Art Whitelist verwenden.
