### ISSUE TITLE
Problem mit der for-in-Schleife

### ISSUE THREAD

**Issue by ACertainCoder** [DaniSchenk/moment-feiertage#15]
Hallo, mir ist per Zufall dieses Fehler aufgefallen:
```
TypeError: Cannot read property 'length' of undefined
at _isHoliday106 (%PROJECT%\node_modules\moment-feiertage\build\index.js:53:39)
at _isHoliday (%PROJECT%\node_modules\moment-feiertage\build\index.js:85:23)
```
moment: ^2.29.1
moment-duration-format: ^2.3.2
moment-feiertage: ^2.0.3
`var holiday = moment().isHoliday();`

Ich bin den Part mit dem Debugger durchgegangen und dabei auf eine for-in-Schleife gestoßen. Problem ist, dass diese ebenfalls durch die Prototypen itteriert und dadurch Attribute verarbeitet, die keine Feiertage beinhalten:
![Code_2020-12-14_17-33-32](https://user-images.githubusercontent.com/47316898/102111087-3e575900-3e36-11eb-90df-5cdff274d1d4.png)

Ich habe hier zwei Vorschläge mit denen man das Problem lösen könnte.

1) via Object.keys und for-of:
```js
for (var h of Object.keys(holidays)) {
    if (_moment.isSame(holidays[h].date, 'day')) {
        if (holidays[h].state.length === 0) {
            return h;
        }
        else {
            if (_state && holidays[h].state.indexOf(_state) > -1) {
                return h;
            }
            else {
                return false;
            }
        }
    }
}
```
2) via Object.entries und for-of
```js
for(var [h, data] of Object.entries(holidays)) {
    if (_moment.isSame(data.date, 'day')) {
        if (data.state.length === 0) {
            return h;
        }
        else {
            if (_state && data.state.indexOf(_state) > -1) {
                return h;
            }
            else {
                return false;
            }
        }
    }
}
```

Mit diesen Änderungen funktionierte das Modul bei mir wieder.
\- ggf. erstelle ich auch gerne einen Pull Request

Viele Grüße
ACertainCoder

**Comment by DaniSchenk** [comment]
@ACertainCoder danke für denk Bug Report und die Vorschläge. Ich würde Version 1 bevorzugen.

PRs sind immer willkommen. Genial wäre zusätzlich auch ein Unit Test, der auf deine Fehlerbehebung prüft.
