### ISSUE TITLE
ACHTUNG!!! Reformationstag wird einmalig am 31.10.2017 ein bundesweiter Feiertag 

### ISSUE THREAD

**Issue by obiwarn** [DaniSchenk/moment-feiertage#4]
Das ist glaube cih nciht drinne.

Feiertage Deutschland » Reformationstag
Reformationstag in Deutschland
Achtung: Anlässlich des 500jährigen Jubiläums von Martin Luthers Thesenanschlag: Der Reformationstag wird einmalig am 31.10.2017 ein bundesweiter Feiertag sein.

**Comment by DaniSchenk** [comment]
@obiwarn danke für den Hinweis. Werde ihn die Tage adden

**Comment by DaniSchenk** [comment]
added: ff9051270d3376ace75464d46f1689ddeaca286a
