### ISSUE TITLE
React native support

### ISSUE THREAD

**Issue by uncledent** [DaniSchenk/moment-feiertage#7]
On react-native isHoliday() is always undefined. Any idea how to add RN support?

**Comment by DaniSchenk** [comment]
Hey @uncledent,
I could not reproduce your issue. With using a fresh installation everything worked as expected. My steps:
```
npm install -g expo-cli
expo init AwesomeProject
cd AwesomeProject
npm install moment moment-feiertage --save
npm start
```
bevore starting I added these lines in `App.js`:
```
import moment from 'moment';
import 'moment-feiertage';

export default class App extends React.Component {
  constructor(props) {
    super(props);
    console.log(moment().isHoliday([]));
  }

  render() { ...
```

I'm not familiar with react-native, so maybe I'm missing something. The `isHoliday()` function returned the correct object anyway. Let me know if you could solve your error. Cheers!

**Comment by DaniSchenk** [comment]
@uncledent I'm closing this issue due inactivity. Fell free to reopen it, if there's any news or questions...
